/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ilmiobis;

//import com.mysql.jdbc.Statement;
//import ilmiobis.Ilmiobis;
import static ilmiobis.Haldatajadwal.getTanggalFromTable;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.HashMap;
import net.sf.Jasperreports.engine.JasperfillManager;
import net.sf.Jasperreports.engine.JasperPrint;
import net.sf.Jasperreports.engine.JasperReport;
import net.sf.Jasperreports.view.JasperViewer;
import net.sf.Jasperreports.engine.JaspercompileManager;

/**
 *
 * @author Afifah
 */
public class Halbooking extends javax.swing.JFrame {
    
    private void kosongkan_form(){
        txtidbooking.setEditable(true);
        txtidbooking.setText(null);
        txtnama.setText(null);
        txttanggal.setDate(null);
        cmbtujuan.setSelectedItem(null);
        cmbasal.setSelectedItem(null);
        cmbjam.setSelectedItem(null);
        cmbjenis.setSelectedItem(null);
        cmbkelas.setSelectedItem(null);
        txtharga.setText(null);
    }
    
    
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("TANGGAL");
        model.addColumn("TUJUAN");
        model.addColumn("ASAL");
        model.addColumn("JAM");
        model.addColumn("JENIS");
        model.addColumn("KELAS");
        model.addColumn("HARGA");
        
        try{
            int no  = 1;
            String sql = "SELECT * From formbooking";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
            model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9)});
            tabelbooking.setModel(model);}
        }catch(SQLException e){
            System.out.println("Error:" + e.getMessage());
        }
    }
    
    public static Date getTanggalFromTable(JTable table, int kolom){
        JTable tabel = table;
        String str_tgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(),kolom));
        Date tanggal = null;
        try{
            tanggal = new SimpleDateFormat("yyy-MM-dd").parse(str_tgl);
            
        }catch(ParseException ex){
            Logger.getLogger(Haldatajadwal.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        return tanggal;
    }
    
   
    
       

    
    /**
     * Creates new form Login
     */
    
    public Halbooking() {
        initComponents();
        tampilkan_data();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelcetaktiket1 = new javax.swing.JLabel();
        labelcetaktiket = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        labelmenu3 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        labeltambah3 = new javax.swing.JLabel();
        labelsimpan3 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        cmbkelas = new javax.swing.JComboBox<>();
        btncetaktiket = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        cmbjenis = new javax.swing.JComboBox<>();
        labelkeluar4 = new javax.swing.JLabel();
        labeledit3 = new javax.swing.JLabel();
        JLabel6 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        cmbjam = new javax.swing.JComboBox<>();
        txtidbooking = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        btnbatal = new javax.swing.JButton();
        labelhapus3 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        cmbtujuan = new javax.swing.JComboBox<>();
        cmbasal = new javax.swing.JComboBox<>();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        txttanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelbooking = new javax.swing.JTable();
        txtharga = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        btnkeluar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelcetaktiket1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        labelcetaktiket1.setForeground(new java.awt.Color(255, 255, 255));
        labelcetaktiket1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcetaktiket1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/iconbusmini.png"))); // NOI18N
        labelcetaktiket1.setFocusable(false);
        labelcetaktiket1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelcetaktiket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 90, 50));

        labelcetaktiket.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        labelcetaktiket.setForeground(new java.awt.Color(255, 255, 255));
        labelcetaktiket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcetaktiket.setText("CETAK TIKET");
        labelcetaktiket.setFocusable(false);
        labelcetaktiket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelcetaktiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 90, 40));

        jLabel59.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("BOOKING TIKET");
        jLabel59.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel59FocusGained(evt);
            }
        });
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 290, 80));

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/User-Interface-Exit-icon.png"))); // NOI18N
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 30));

        labelmenu3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelmenu3.setForeground(new java.awt.Color(51, 37, 78));
        labelmenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelmenu3.setText("MENU");
        labelmenu3.setFocusable(false);
        labelmenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelmenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, 30));

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/icontrash.png"))); // NOI18N
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 30, 30));

        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/Pencil-icon.png"))); // NOI18N
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 40, 30));

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/User-Interface-Exit-icon.png"))); // NOI18N
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 40, 30));

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/closeicon.png"))); // NOI18N
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 30, 30));

        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/save-icon.png"))); // NOI18N
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 40, 30));
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 80, -1));

        labeltambah3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labeltambah3.setForeground(new java.awt.Color(51, 37, 78));
        labeltambah3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltambah3.setText("BATAL");
        labeltambah3.setFocusable(false);
        labeltambah3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labeltambah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 80, 30));

        labelsimpan3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelsimpan3.setForeground(new java.awt.Color(51, 37, 78));
        labelsimpan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsimpan3.setText("SIMPAN");
        labelsimpan3.setFocusable(false);
        labelsimpan3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelsimpan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 70, 30));

        jLabel67.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Nama Penumpang");
        jLabel67.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel67FocusGained(evt);
            }
        });
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        cmbkelas.setBackground(new java.awt.Color(156, 42, 225));
        cmbkelas.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbkelas.setForeground(new java.awt.Color(255, 255, 255));
        cmbkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Ekonomi", "Ekonomi AC", "Bisnis", "Executive", "Executive Plus", "Super Executive", " " }));
        jPanel1.add(cmbkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 190, -1));

        btncetaktiket.setBackground(new java.awt.Color(51, 37, 78));
        btncetaktiket.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btncetaktiket.setForeground(new java.awt.Color(51, 37, 78));
        btncetaktiket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/Rectangle 1.png"))); // NOI18N
        btncetaktiket.setBorder(null);
        btncetaktiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetaktiketActionPerformed(evt);
            }
        });
        jPanel1.add(btncetaktiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 90, 90));

        btnmenu.setBackground(new java.awt.Color(51, 37, 78));
        btnmenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnmenu.setForeground(new java.awt.Color(51, 37, 78));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/btnSignUpSwitch2.png"))); // NOI18N
        btnmenu.setBorder(null);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        jLabel68.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Jenis Bus");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 190, 20));

        cmbjenis.setBackground(new java.awt.Color(156, 42, 225));
        cmbjenis.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbjenis.setForeground(new java.awt.Color(255, 255, 255));
        cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "XBUS", "Sumber Kencana", "BARAYA", "Harapan Jaya", "Damri", "Lintas JABODETABEK", "Perum PPD", "HEI TAYO", "CIPAGANTI", "BAHAGIA SELALU" }));
        jPanel1.add(cmbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 190, -1));

        labelkeluar4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelkeluar4.setForeground(new java.awt.Color(51, 37, 78));
        labelkeluar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelkeluar4.setText("KELUAR");
        labelkeluar4.setFocusable(false);
        labelkeluar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelkeluar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 60, 30));

        labeledit3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labeledit3.setForeground(new java.awt.Color(51, 37, 78));
        labeledit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeledit3.setText("EDIT");
        labeledit3.setFocusable(false);
        labeledit3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labeledit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 80, 30));

        JLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        JLabel6.setForeground(new java.awt.Color(255, 255, 255));
        JLabel6.setText("Tujuan");
        jPanel1.add(JLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 20));

        jLabel69.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Come and Go With Us");
        jLabel69.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel69FocusGained(evt);
            }
        });
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, 20));

        cmbjam.setBackground(new java.awt.Color(156, 42, 225));
        cmbjam.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbjam.setForeground(new java.awt.Color(255, 255, 255));
        cmbjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "07.00", "09.00", "11.00", "13.00", "15.00", "17.00", "19.00", "21.00", "23.00" }));
        jPanel1.add(cmbjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, -1));

        txtidbooking.setBackground(new java.awt.Color(51, 37, 78));
        txtidbooking.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtidbooking.setForeground(new java.awt.Color(153, 153, 153));
        txtidbooking.setText("Enter ID Booking");
        txtidbooking.setBorder(null);
        txtidbooking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidbookingFocusGained(evt);
            }
        });
        txtidbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidbookingActionPerformed(evt);
            }
        });
        jPanel1.add(txtidbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 20));

        jLabel70.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Jam Keberangkatan");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, 20));

        btnbatal.setBackground(new java.awt.Color(51, 37, 78));
        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/btnSignUpSwitch2.png"))); // NOI18N
        btnbatal.setBorder(null);
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
        });
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 90, 30));

        labelhapus3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelhapus3.setForeground(new java.awt.Color(51, 37, 78));
        labelhapus3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhapus3.setText("HAPUS");
        labelhapus3.setFocusable(false);
        labelhapus3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelhapus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 80, 30));

        btnhapus.setBackground(new java.awt.Color(51, 37, 78));
        btnhapus.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(51, 37, 78));
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/btnSignUpSwitch2.png"))); // NOI18N
        btnhapus.setBorder(null);
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
        });
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 90, 30));

        jLabel71.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Harga");
        jLabel71.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel71FocusGained(evt);
            }
        });
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, 20));

        jLabel73.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("ID Booking");
        jLabel73.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel73FocusGained(evt);
            }
        });
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel74.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Tanggal Keberangkatan");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, -1));

        jLabel75.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Asal");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 20));

        cmbtujuan.setBackground(new java.awt.Color(156, 42, 225));
        cmbtujuan.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbtujuan.setForeground(new java.awt.Color(255, 255, 255));
        cmbtujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Jakarta", "Depok", "Bekasi", "Tangerang", "Bandung", "Bogor", "Banten", "Tasikmalaya", "Karawang", "Cikarang", "Purwakarta", " " }));
        jPanel1.add(cmbtujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 190, -1));

        cmbasal.setBackground(new java.awt.Color(156, 42, 225));
        cmbasal.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbasal.setForeground(new java.awt.Color(255, 255, 255));
        cmbasal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Jakarta", "Depok", "Bekasi", "Tangerang", "Bandung", "Bogor", "Tasikmalaya", "Karawang", "Cikarang", "Banten", "Purwakarta" }));
        jPanel1.add(cmbasal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, -1));

        btnedit.setBackground(new java.awt.Color(51, 37, 78));
        btnedit.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(51, 37, 78));
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/btnSignUpSwitch2.png"))); // NOI18N
        btnedit.setBorder(null);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 90, 30));

        btnsimpan.setBackground(new java.awt.Color(51, 37, 78));
        btnsimpan.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(51, 37, 78));
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/btnSignUpSwitch2.png"))); // NOI18N
        btnsimpan.setBorder(null);
        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpanMouseClicked(evt);
            }
        });
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 90, 30));
        jPanel1.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, -1));

        tabelbooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbookingMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelbooking);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 480, 250));

        txtharga.setBackground(new java.awt.Color(51, 37, 78));
        txtharga.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtharga.setForeground(new java.awt.Color(153, 153, 153));
        txtharga.setText("Harga");
        txtharga.setBorder(null);
        txtharga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txthargaFocusGained(evt);
            }
        });
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 190, -1));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Kelas Bus");
        jLabel19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel19FocusGained(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 20));

        txtnama.setBackground(new java.awt.Color(51, 37, 78));
        txtnama.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(153, 153, 153));
        txtnama.setText("Enter Nama Penumpang");
        txtnama.setBorder(null);
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
        });
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 190, 20));

        btnkeluar.setBackground(new java.awt.Color(51, 37, 78));
        btnkeluar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnkeluar.setForeground(new java.awt.Color(51, 37, 78));
        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/btnSignUpSwitch2.png"))); // NOI18N
        btnkeluar.setBorder(null);
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PBOOOO/bgungu.png"))); // NOI18N
        jLabel4.setText("ddd");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
        txtnama.setText("");
    }//GEN-LAST:event_txtnamaFocusGained

    private void jLabel19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel19FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19FocusGained

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txthargaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthargaFocusGained
        // TODO add your handling code here:
        txtharga.setText("");
    }//GEN-LAST:event_txthargaFocusGained

    private void tabelbookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbookingMouseClicked
        // TODO add your handling code here:
        int baris = tabelbooking.rowAtPoint(evt.getPoint());
        
        String id = tabelbooking.getValueAt(baris, 1).toString();
        txtidbooking.setText(id);
        
        String nama = tabelbooking.getValueAt(baris, 2).toString();
        txtnama.setText(nama);
        
        txttanggal.setDate(getTanggalFromTable(tabelbooking, 3));
        
        String tujuan = tabelbooking.getValueAt(baris, 4).toString();
        cmbtujuan.setSelectedItem(tujuan);
        
        String asal = tabelbooking.getValueAt(baris, 5).toString();
        cmbasal.setSelectedItem(asal);
        
        String jam = tabelbooking.getValueAt(baris, 6).toString();
        cmbjam.setSelectedItem(jam);
        
        String jenis = tabelbooking.getValueAt(baris, 7).toString();
        cmbjenis.setSelectedItem(jenis);
        
        String kelas = tabelbooking.getValueAt(baris, 8).toString();
        cmbkelas.setSelectedItem(kelas);
        
        String harga = tabelbooking.getValueAt(baris, 9).toString();
        txtharga.setText(harga);
    }//GEN-LAST:event_tabelbookingMouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txttanggal.getDate()));
        
        try{
            String sql = "INSERT INTO formbooking VALUE ('"+txtidbooking.getText()+"','"+txtnama.getText()+"','"+tanggal +"','"+cmbtujuan.getSelectedItem()+"','"+cmbasal.getSelectedItem()+"','"+cmbjam.getSelectedItem()+"','"+cmbjenis.getSelectedItem()+"','"+cmbkelas.getSelectedItem()+"','"+txtharga.getText()+"')";
            java.sql.Connection con = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "SIMPAN DATA BERHASIL");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, "SIMPAN DATA GAGAL");
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpanMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txttanggal.getDate()));
        try{
            String sql = "INSERT formbooking set id ='"+ txtidbooking.getText()+"',nama ='"+ txtnama.getText()+"', tanggal ='"+ tanggal +"',tujuan ='"+ cmbtujuan.getSelectedItem()+"',asal ='"+ cmbasal.getSelectedItem()+"',jam ='"+ cmbjam.getSelectedItem()+"',jenis ='"+ cmbjenis.getSelectedItem()+"',kelas ='"+ cmbkelas.getSelectedItem()+"',harga ='"+ txtharga.getText()+"' On Duplicate Key Update id ='"+ txtidbooking.getText()+"',nama ='"+ txtnama.getText()+"', tanggal ='"+ tanggal +"',tujuan ='"+ cmbtujuan.getSelectedItem()+"',asal ='"+ cmbasal.getSelectedItem()+"',jam ='"+ cmbjam.getSelectedItem()+"',jenis ='"+ cmbjenis.getSelectedItem()+"',kelas ='"+ cmbkelas.getSelectedItem()+"',harga ='"+ txtharga.getText()+"'"; 
            java.sql.Connection conn= (Connection)Konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "EDIT DATA BERHASIL");
                    
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_btneditActionPerformed

    private void jLabel73FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel73FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel73FocusGained

    private void jLabel71FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel71FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel71FocusGained

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusMouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbatalMouseClicked

    private void txtidbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidbookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidbookingActionPerformed

    private void txtidbookingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidbookingFocusGained
        // TODO add your handling code here:
        txtidbooking.setText("");
    }//GEN-LAST:event_txtidbookingFocusGained

    private void jLabel69FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel69FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel69FocusGained

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        new Halmenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btncetaktiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetaktiketActionPerformed
        // TODO add your handling code here:
        java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);
            
            String url = "jdbc:mysql://localhost:3306/ilmiobis";
            String user = "root";
            String pass = "";
            
            con = DriverManager.getConnection(url,user,pass);
            Statement stm = con.createStatement();
            
            try{
                String report = ("C:\\Users\\Afifah\\Documents\\NetBeansProjects\\Ilmiobis\\src\\ilmiobis\\struk.jrxml");
                HashMap hash = new HashMap();
                hash.put ("idbooking", txtidbooking.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash,con);
                JasperViewer.viewReport(JPrint, false);
            }catch(Exception rptexcpt){
                System.out.print("Report Can't view because:"+rptexcpt); 
            }
        }catch(Exception e){
            System.out.println(e);  
        }   
    }//GEN-LAST:event_btncetaktiketActionPerformed

    private void jLabel67FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel67FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel67FocusGained

    private void jLabel59FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel59FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel59FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halbooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel6;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncetaktiket;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbasal;
    private javax.swing.JComboBox<String> cmbjam;
    private javax.swing.JComboBox<String> cmbjenis;
    private javax.swing.JComboBox<String> cmbkelas;
    private javax.swing.JComboBox<String> cmbtujuan;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel labelcetaktiket;
    private javax.swing.JLabel labelcetaktiket1;
    private javax.swing.JLabel labeledit3;
    private javax.swing.JLabel labelhapus3;
    private javax.swing.JLabel labelkeluar4;
    private javax.swing.JLabel labelmenu3;
    private javax.swing.JLabel labelsimpan3;
    private javax.swing.JLabel labeltambah3;
    public javax.swing.JTable tabelbooking;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidbooking;
    private javax.swing.JTextField txtnama;
    private com.toedter.calendar.JDateChooser txttanggal;
    // End of variables declaration//GEN-END:variables
}
