/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ilmiobis;

//import com.mysql.jdbc.Statement;
//import ilmiobis.Ilmiobis;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Afifah
 */
public class Haldatabus extends javax.swing.JFrame {
    
    
    private void kosongkan_form(){
        txtid.setEditable(true);
        txtid.setText(null);
        txtnama.setText(null);
        cmbkelas.setSelectedItem(null);
        txtnopol.setText(null);
        txtharga.setText(null);
        cmbstatus.setSelectedItem(null);
    }
    
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("KELAS");
        model.addColumn("NO POLISI");
        model.addColumn("HARGA");
        model.addColumn("STATUS");
        
        try{
            int no  = 1;
            String sql = "SELECT * From formdatabus";
            java.sql.Connection conn=(Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
            model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            tabeljadwal.setModel(model);}
        }catch(SQLException e){
            System.out.println("Error:" + e.getMessage());
        }
    }
    
    /**
     * Creates new form Login
     */
    
    public Haldatabus() {
        initComponents();
        tampilkan_data();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelmenu = new javax.swing.JLabel();
        btnmenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtharga = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        txtnopol = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        labeltambah = new javax.swing.JLabel();
        labelkeluar = new javax.swing.JLabel();
        labelsimpan = new javax.swing.JLabel();
        labeledit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnbatal = new javax.swing.JButton();
        labelhapus = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cmbkelas = new javax.swing.JComboBox<>();
        cmbstatus = new javax.swing.JComboBox<>();
        btnkeluar = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeljadwal = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Data Bus");
        jLabel22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel22FocusGained(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 340, 50));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\User-Interface-Exit-icon.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        labelmenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelmenu.setForeground(new java.awt.Color(51, 37, 78));
        labelmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelmenu.setText("MENU");
        labelmenu.setFocusable(false);
        labelmenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 30));

        btnmenu.setBackground(new java.awt.Color(51, 37, 78));
        btnmenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnmenu.setForeground(new java.awt.Color(51, 37, 78));
        btnmenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\btnSignUpSwitch2.png")); // NOI18N
        btnmenu.setBorder(null);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\icontrash.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 30, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\Pencil-icon.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 40, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\User-Interface-Exit-icon.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 40, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\closeicon.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 30, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\save-icon.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\iconbusmini.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 80, -1));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nama Bus");
        jLabel16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel16FocusGained(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 20));

        txtnama.setBackground(new java.awt.Color(51, 37, 78));
        txtnama.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(153, 153, 153));
        txtnama.setText("Enter Nama");
        txtnama.setBorder(null);
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
        });
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 10));

        txtharga.setBackground(new java.awt.Color(51, 37, 78));
        txtharga.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtharga.setForeground(new java.awt.Color(153, 153, 153));
        txtharga.setText("Enter Harga");
        txtharga.setBorder(null);
        txtharga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txthargaFocusGained(evt);
            }
        });
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, 10));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Harga");
        jLabel18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel18FocusGained(evt);
            }
        });
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 190, 20));

        txtnopol.setBackground(new java.awt.Color(51, 37, 78));
        txtnopol.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtnopol.setForeground(new java.awt.Color(153, 153, 153));
        txtnopol.setText("Enter No Polisi");
        txtnopol.setBorder(null);
        txtnopol.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnopolFocusGained(evt);
            }
        });
        txtnopol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnopolActionPerformed(evt);
            }
        });
        jPanel1.add(txtnopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, 10));

        labeltambah.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labeltambah.setForeground(new java.awt.Color(51, 37, 78));
        labeltambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltambah.setText("BATAL");
        labeltambah.setFocusable(false);
        labeltambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labeltambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 80, 30));

        labelkeluar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelkeluar.setForeground(new java.awt.Color(51, 37, 78));
        labelkeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelkeluar.setText("KELUAR");
        labelkeluar.setFocusable(false);
        labelkeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 60, 30));

        labelsimpan.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelsimpan.setForeground(new java.awt.Color(51, 37, 78));
        labelsimpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsimpan.setText("SIMPAN");
        labelsimpan.setFocusable(false);
        labelsimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 70, 30));

        labeledit.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labeledit.setForeground(new java.awt.Color(51, 37, 78));
        labeledit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeledit.setText("EDIT");
        labeledit.setFocusable(false);
        labeledit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labeledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 80, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Come and Go With Us");
        jLabel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel6FocusGained(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, 20));

        btnbatal.setBackground(new java.awt.Color(51, 37, 78));
        btnbatal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\btnSignUpSwitch2.png")); // NOI18N
        btnbatal.setBorder(null);
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
        });
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 90, 30));

        labelhapus.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelhapus.setForeground(new java.awt.Color(51, 37, 78));
        labelhapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhapus.setText("HAPUS");
        labelhapus.setFocusable(false);
        labelhapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 80, 30));

        btnhapus.setBackground(new java.awt.Color(51, 37, 78));
        btnhapus.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(51, 37, 78));
        btnhapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\btnSignUpSwitch2.png")); // NOI18N
        btnhapus.setBorder(null);
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
        });
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 90, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 10));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 37, 78));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("No Polisi");
        jLabel14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel14FocusGained(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 20));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID Bus");
        jLabel15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel15FocusGained(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 20));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kelas Bus");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, -1));

        txtid.setBackground(new java.awt.Color(51, 37, 78));
        txtid.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(153, 153, 153));
        txtid.setText("Enter ID Bus");
        txtid.setBorder(null);
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, -1));

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Status");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 80, 20));

        cmbkelas.setBackground(new java.awt.Color(156, 42, 225));
        cmbkelas.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbkelas.setForeground(new java.awt.Color(255, 255, 255));
        cmbkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Ekonomi", "Ekonomi AC", "Bisnis", "Executive", "Executive Plus", "Super Executive", " " }));
        jPanel1.add(cmbkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, -1));

        cmbstatus.setBackground(new java.awt.Color(156, 42, 225));
        cmbstatus.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cmbstatus.setForeground(new java.awt.Color(255, 255, 255));
        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Ready", "Not Ready" }));
        jPanel1.add(cmbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 190, -1));

        btnkeluar.setBackground(new java.awt.Color(51, 37, 78));
        btnkeluar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnkeluar.setForeground(new java.awt.Color(51, 37, 78));
        btnkeluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\btnSignUpSwitch2.png")); // NOI18N
        btnkeluar.setBorder(null);
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 90, 30));

        btnedit.setBackground(new java.awt.Color(51, 37, 78));
        btnedit.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(51, 37, 78));
        btnedit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\btnSignUpSwitch2.png")); // NOI18N
        btnedit.setBorder(null);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 90, 30));

        btnsimpan.setBackground(new java.awt.Color(51, 37, 78));
        btnsimpan.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(51, 37, 78));
        btnsimpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Documents\\PBO\\btnSignUpSwitch2.png")); // NOI18N
        btnsimpan.setBorder(null);
        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpanMouseClicked(evt);
            }
        });
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 90, 30));

        tabeljadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeljadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeljadwalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeljadwal);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 480, 250));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afifah\\Pictures\\leftPanelBack.png")); // NOI18N
        jLabel4.setText("ddd");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel6FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel6FocusGained

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM formdatabus WHERE id ='" + txtid.getText() + "'";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "HAPUS DATA BERHASIL");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jLabel14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel14FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14FocusGained

    private void jLabel15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15FocusGained

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        // TODO add your handling code here:
        txtid.setText("");
    }//GEN-LAST:event_txtidFocusGained

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

        try{
            String sql = "INSERT INTO formdatabus VALUE ('"+txtid.getText()+"','"+ txtnama.getText() +"','"+cmbkelas.getSelectedItem()+"','"+ txtnopol.getText()+"','"+txtharga.getText()+"','"+cmbstatus.getSelectedItem()+"')";
            java.sql.Connection con = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "SIMPAN DATA BERHASIL");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, "SIMPAN DATA GAGAL");
        }
        tampilkan_data();
        kosongkan_form();

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:

        try{
            String sql = "INSERT formdatabus set id ='"+ txtid.getText()+"',nama ='"+ txtnama.getText() +"',kelas ='"+ cmbkelas.getSelectedItem()+"',nopol ='"+ txtnopol.getText()+"',harga ='"+ txtharga.getText()+"',status ='"+cmbstatus.getSelectedItem()+"' On Duplicate key Update id ='"+ txtid.getText()+"',nama ='"+ txtnama.getText() +"',kelas ='"+ cmbkelas.getSelectedItem()+"',nopol ='"+ txtnopol.getText()+"',harga ='"+ txtharga.getText()+"',status ='"+cmbstatus.getSelectedItem()+"'"; 
            java.sql.Connection conn= (Connection)Konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "EDIT DATA BERHASIL");
                    
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
        //id_dataa();
    }//GEN-LAST:event_btneditActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        kosongkan_form();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnbatalMouseClicked

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusMouseClicked

    private void btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnsimpanMouseClicked

    private void tabeljadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeljadwalMouseClicked
        // TODO add your handling code here:
        int baris = tabeljadwal.rowAtPoint(evt.getPoint());
        
        String id = tabeljadwal.getValueAt(baris, 1).toString();
        txtid.setText(id);
        
        String nama = tabeljadwal.getValueAt(baris, 2).toString();
        txtnama.setText(nama);
        
        String kelas = tabeljadwal.getValueAt(baris, 3).toString();
        cmbkelas.setSelectedItem(kelas);
        
        String nopol = tabeljadwal.getValueAt(baris, 4).toString();
        txtnopol.setText(nopol);
        
        String harga = tabeljadwal.getValueAt(baris, 5).toString();
        txtharga.setText(harga);
        
        String status = tabeljadwal.getValueAt(baris, 6).toString();
        cmbstatus.setSelectedItem(status);
        
    }//GEN-LAST:event_tabeljadwalMouseClicked

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        new Halmenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void jLabel22FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel22FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22FocusGained

    private void jLabel16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel16FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16FocusGained

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaFocusGained

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txthargaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthargaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaFocusGained

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void jLabel18FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel18FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18FocusGained

    private void txtnopolFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnopolFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnopolFocusGained

    private void txtnopolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnopolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnopolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Haldatabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Haldatabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Haldatabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Haldatabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Haldatabus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbkelas;
    private javax.swing.JComboBox<String> cmbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labeledit;
    private javax.swing.JLabel labelhapus;
    private javax.swing.JLabel labelkeluar;
    private javax.swing.JLabel labelmenu;
    private javax.swing.JLabel labelsimpan;
    private javax.swing.JLabel labeltambah;
    public javax.swing.JTable tabeljadwal;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnopol;
    // End of variables declaration//GEN-END:variables
}
